site:
  title: "Felipe Marinho - Timeline"
  description: "Bem vindo a minha timeline pessoal"
personal:
  name: "Felipe Marinho"
  avatar: "https://github.com/felipemarinhodev.png"
  socialnetworks:
    linkedin: "https://linkedin.com/felipemarinhodev"
